### ISSUE TITLE
Hot module reload for tests

### ISSUE THREAD

**Issue by aaronjensen** [codymikol/karma-webpack#78]
Have you given thought to writing a test runner or somehow extending mocha to only run tests for specs that have changed or whose dependencies have changed? It would be a very powerful thing for bigger projects.

**Comment by studds** [comment]
This would be great. I'm not familiar with any of the code bases involved, so I'm not sure just how much I can contribute, but I've be mulling this over conceptually. I thought rather than just put it to one side, I'd write down my thoughts as a straw-man. If someone who is a bit more familiar with how this all works, and can refine this, that would be brilliant.

I'm not sure if "proper" HMR is required for achieve this, or if it is necessarily the easiest way to do it. (Would using HMR mean that jasmine was HMR aware? Or just karma runner?)

**Aims**

1. Only re-run tests which have changed or whose dependencies have changed
2. Don't require whoever is consuming test results to be aware of what we're doing. (ie. return the full result set every time, not just the subset which has changed).

**Design constraints**

1. Only support the "one entry per test file" style, as this will result in one chunk per test-file, which will make it much easier to work out which tests / dependencies have changed.

**Description of what should happen**

1. Start karma in watch mode with one entry per test file
2. webpack builds one output file per test file
3. All the tests are run as per usual
4. The test results are cached on an per test-file basis before being returned
5. webpack picks up changes to tests or dependencies & updates one or more test files
6. karma-webpack sends only these changed files off to karma-runner to be re-run
7. The new results are cached
8. The full result set is returned

**Questions**

1. Is it possible to access test results "per-file" from karma runner?
2. Where ought the test results be cached?
3. Is it possible to only re-run certain files with karma runner at present?
4. Where would we make the change to return cached results, rather than "fresh" results?

**Comment by aaronjensen** [comment]
@studds thank you for your comments. For what it's worth, there's a version that implements this available https://www.npmjs.com/package/karma-webpack-with-fast-source-maps

**Comment by mcm-ham** [comment]
@aaronjensen I like your documentation on sourcemaps it's more clear, it'd be worth considering to update the `karma-webpack` repo to match.

**Comment by aaronjensen** [comment]
Feel free to take whichever bits of the docs you like and PR them to here.

**Comment by gnz00** [comment]
@aaronjensen Seems that the version you linked is no longer supported and incompatible with latest depencies. Any chance this feature can be implemented in this repo?

**Comment by aaronjensen** [comment]
@gnz00 I'm not using Karma anymore, so it's unlikely that I will, but anyone else is totally welcome to.

**Comment by benjamingr** [comment]
@gnz00 what are you using instead?

**Comment by codymikol** [comment]
As karma is now deprecated and coming up on EOL, we are no longer planning on any significant enhancements to this project and are instead going to focus on security updates, stability, and a migration path forward as karma's lifecycle comes to an end.

Thank you for supporting and using this project!
